import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

// Base64 URL encoding/decoding utilities
function base64UrlEncode(data: Uint8Array): string {
  let binary = '';
  for (let i = 0; i < data.byteLength; i++) {
    binary += String.fromCharCode(data[i]);
  }
  return btoa(binary).replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/g, '');
}

function base64UrlDecode(str: string): Uint8Array {
  let base64 = str.replace(/-/g, '+').replace(/_/g, '/');
  while (base64.length % 4) base64 += '=';
  const binary = atob(base64);
  return new Uint8Array([...binary].map(c => c.charCodeAt(0)));
}

// Create JWT for VAPID authentication
async function createVapidJwt(audience: string, subject: string, privateKeyBase64: string): Promise<string> {
  const header = { alg: 'ES256', typ: 'JWT' };
  const now = Math.floor(Date.now() / 1000);
  const payload = {
    aud: audience,
    exp: now + 86400,
    sub: subject
  };

  const headerB64 = base64UrlEncode(new TextEncoder().encode(JSON.stringify(header)));
  const payloadB64 = base64UrlEncode(new TextEncoder().encode(JSON.stringify(payload)));
  const unsignedToken = `${headerB64}.${payloadB64}`;

  // Import the private key in PKCS8 format (as generated by generate-vapid-keys)
  const privateKeyBytes = base64UrlDecode(privateKeyBase64);
  
  console.log('[VAPID JWT] Importing private key, length:', privateKeyBytes.length);
  
  const cryptoKey = await crypto.subtle.importKey(
    'pkcs8',
    privateKeyBytes.buffer as ArrayBuffer,
    { name: 'ECDSA', namedCurve: 'P-256' },
    false,
    ['sign']
  );

  // Sign the token
  const signatureRaw = await crypto.subtle.sign(
    { name: 'ECDSA', hash: 'SHA-256' },
    cryptoKey,
    new TextEncoder().encode(unsignedToken)
  );

  // Convert DER signature to raw R||S format for JWT
  const signatureBytes = new Uint8Array(signatureRaw);
  let r: Uint8Array, s: Uint8Array;
  
  // Web Crypto returns raw R||S format (64 bytes)
  if (signatureBytes.length === 64) {
    r = signatureBytes.slice(0, 32);
    s = signatureBytes.slice(32, 64);
  } else {
    // Fallback: parse as DER if needed
    r = signatureBytes.slice(0, 32);
    s = signatureBytes.slice(32);
  }
  
  const jwtSignature = new Uint8Array(64);
  jwtSignature.set(r, 0);
  jwtSignature.set(s, 32);

  const signatureB64 = base64UrlEncode(jwtSignature);
  return `${unsignedToken}.${signatureB64}`;
}

// Generate encryption keys for push payload
async function generateEncryptionKeys() {
  const localKeyPair = await crypto.subtle.generateKey(
    { name: 'ECDH', namedCurve: 'P-256' },
    true,
    ['deriveBits']
  );

  const salt = crypto.getRandomValues(new Uint8Array(16));
  const publicKeyBuffer = await crypto.subtle.exportKey('raw', localKeyPair.publicKey);
  
  return {
    localKeyPair,
    salt,
    localPublicKey: new Uint8Array(publicKeyBuffer)
  };
}

// HKDF implementation for key derivation
async function hkdfDerive(
  ikm: Uint8Array,
  salt: Uint8Array,
  info: Uint8Array,
  length: number
): Promise<Uint8Array> {
  const hkdfKey = await crypto.subtle.importKey(
    'raw',
    ikm.buffer as ArrayBuffer,
    'HKDF',
    false,
    ['deriveBits']
  );

  const derived = await crypto.subtle.deriveBits(
    {
      name: 'HKDF',
      hash: 'SHA-256',
      salt: salt.buffer as ArrayBuffer,
      info: info.buffer as ArrayBuffer
    },
    hkdfKey,
    length * 8
  );

  return new Uint8Array(derived);
}

// Derive encryption key using ECDH
async function deriveEncryptionKey(
  localPrivateKey: CryptoKey,
  clientPublicKeyBytes: Uint8Array,
  authSecret: Uint8Array,
  salt: Uint8Array,
  localPublicKey: Uint8Array
): Promise<{ contentEncryptionKey: Uint8Array; nonce: Uint8Array }> {
  // Import client public key
  const clientPublicKey = await crypto.subtle.importKey(
    'raw',
    clientPublicKeyBytes.buffer as ArrayBuffer,
    { name: 'ECDH', namedCurve: 'P-256' },
    false,
    []
  );

  // Derive shared secret via ECDH
  const sharedSecretBits = await crypto.subtle.deriveBits(
    { name: 'ECDH', public: clientPublicKey },
    localPrivateKey,
    256
  );
  const sharedSecret = new Uint8Array(sharedSecretBits);

  // WebPush key derivation (RFC 8291)
  const authInfo = new Uint8Array([
    ...new TextEncoder().encode('WebPush: info\0'),
    ...clientPublicKeyBytes,
    ...localPublicKey
  ]);

  // PRK = HKDF-Extract(auth_secret, ecdh_secret)
  // Then derive IKM = HKDF-Expand(PRK, auth_info, 32)
  const prk = await hkdfDerive(sharedSecret, authSecret, authInfo, 32);

  // Derive CEK and Nonce
  const cekInfo = new TextEncoder().encode('Content-Encoding: aes128gcm\0');
  const nonceInfo = new TextEncoder().encode('Content-Encoding: nonce\0');

  const contentEncryptionKey = await hkdfDerive(prk, salt, cekInfo, 16);
  const nonce = await hkdfDerive(prk, salt, nonceInfo, 12);

  return { contentEncryptionKey, nonce };
}

// Encrypt the payload using AES-GCM
async function encryptPayload(
  payload: string,
  clientPublicKeyBytes: Uint8Array,
  authSecret: Uint8Array
): Promise<{ encrypted: Uint8Array; salt: Uint8Array; localPublicKey: Uint8Array }> {
  const { localKeyPair, salt, localPublicKey } = await generateEncryptionKeys();

  const { contentEncryptionKey, nonce } = await deriveEncryptionKey(
    localKeyPair.privateKey,
    clientPublicKeyBytes,
    authSecret,
    salt,
    localPublicKey
  );

  // Import CEK for AES-GCM
  const aesKey = await crypto.subtle.importKey(
    'raw',
    contentEncryptionKey.buffer as ArrayBuffer,
    'AES-GCM',
    false,
    ['encrypt']
  );

  // Add padding delimiter (0x02 for final record)
  const payloadBytes = new TextEncoder().encode(payload);
  const paddedPayload = new Uint8Array(payloadBytes.length + 1);
  paddedPayload.set(payloadBytes);
  paddedPayload[payloadBytes.length] = 0x02; // Final record delimiter

  // Encrypt
  const encrypted = await crypto.subtle.encrypt(
    { name: 'AES-GCM', iv: nonce.buffer as ArrayBuffer },
    aesKey,
    paddedPayload
  );

  return {
    encrypted: new Uint8Array(encrypted),
    salt,
    localPublicKey
  };
}

// Build the encrypted body in aes128gcm format
function buildAes128gcmBody(
  encrypted: Uint8Array,
  salt: Uint8Array,
  localPublicKey: Uint8Array
): ArrayBuffer {
  // Header: salt (16) + rs (4) + keylen (1) + key (65)
  const header = new Uint8Array(86);
  
  // Salt (16 bytes)
  header.set(salt, 0);
  
  // Record size (4 bytes, big-endian) - max payload size
  const recordSize = 4096;
  const view = new DataView(header.buffer);
  view.setUint32(16, recordSize, false);
  
  // Key length (1 byte)
  header[20] = localPublicKey.length;
  
  // Public key (65 bytes for uncompressed P-256)
  header.set(localPublicKey, 21);
  
  // Combine header + encrypted data
  const body = new Uint8Array(header.length + encrypted.length);
  body.set(header, 0);
  body.set(encrypted, header.length);
  
  return body.buffer as ArrayBuffer;
}

async function sendPushNotification(
  subscription: { endpoint: string; p256dh: string; auth: string },
  payload: string,
  vapidPublicKey: string,
  vapidPrivateKey: string
): Promise<{ success: boolean; error?: string; statusCode?: number }> {
  try {
    const url = new URL(subscription.endpoint);
    const audience = `${url.protocol}//${url.host}`;

    console.log('[Push] Creating VAPID JWT for audience:', audience);
    const jwt = await createVapidJwt(audience, 'mailto:admin@platform.com', vapidPrivateKey);

    const clientPublicKey = base64UrlDecode(subscription.p256dh);
    const authSecret = base64UrlDecode(subscription.auth);

    console.log('[Push] Encrypting payload...');
    const { encrypted, salt, localPublicKey } = await encryptPayload(
      payload,
      clientPublicKey,
      authSecret
    );

    const body = buildAes128gcmBody(encrypted, salt, localPublicKey);
    console.log('[Push] Body size:', body.byteLength, 'bytes');

    const response = await fetch(subscription.endpoint, {
      method: 'POST',
      headers: {
        'Authorization': `vapid t=${jwt}, k=${vapidPublicKey}`,
        'Content-Encoding': 'aes128gcm',
        'Content-Type': 'application/octet-stream',
        'TTL': '86400',
        'Urgency': 'normal'
      },
      body: body
    });

    console.log('[Push] Response status:', response.status);

    if (!response.ok) {
      const text = await response.text();
      console.log('[Push] Error response:', text);
      return { success: false, error: `HTTP ${response.status}: ${text}`, statusCode: response.status };
    }

    return { success: true, statusCode: response.status };
  } catch (error) {
    console.error('[Push] Exception:', error);
    return { success: false, error: error instanceof Error ? error.message : String(error) };
  }
}

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { 
      title, 
      body, 
      icon, 
      url, 
      userId, 
      sendToAll = false,
      tag = 'platform-notification'
    } = await req.json();

    console.log('[Send Push] Request:', { title, userId, sendToAll });

    if (!title || !body) {
      return new Response(
        JSON.stringify({ error: 'Missing required fields: title, body' }),
        { status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    const vapidPublicKey = Deno.env.get('VAPID_PUBLIC_KEY');
    const vapidPrivateKey = Deno.env.get('VAPID_PRIVATE_KEY');
    
    if (!vapidPublicKey || !vapidPrivateKey) {
      console.error('[Send Push] VAPID keys not configured');
      return new Response(
        JSON.stringify({ error: 'VAPID keys not configured. Please generate and configure VAPID keys in the admin panel.' }),
        { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    console.log('[Send Push] VAPID public key length:', vapidPublicKey.length);
    console.log('[Send Push] VAPID private key length:', vapidPrivateKey.length);

    const supabaseUrl = Deno.env.get('SUPABASE_URL')!;
    const supabaseServiceKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
    const supabase = createClient(supabaseUrl, supabaseServiceKey);

    let query = supabase.from('push_subscriptions').select('*');
    
    if (!sendToAll && userId) {
      query = query.eq('user_id', userId);
    }
    
    const { data: subscriptions, error: queryError } = await query;
    
    if (queryError) {
      console.error('[Send Push] Error fetching subscriptions:', queryError);
      throw queryError;
    }

    if (!subscriptions || subscriptions.length === 0) {
      console.log('[Send Push] No subscriptions found');
      return new Response(
        JSON.stringify({ success: true, sent: 0, message: 'No subscriptions found' }),
        { status: 200, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    console.log(`[Send Push] Sending to ${subscriptions.length} subscriptions`);

    const notificationPayload = JSON.stringify({
      title,
      body,
      icon: icon || '/pwa-192x192.png',
      badge: '/pwa-192x192.png',
      url: url || '/',
      tag,
      timestamp: Date.now()
    });

    let sent = 0;
    let failed = 0;
    const errors: string[] = [];

    for (const sub of subscriptions) {
      const result = await sendPushNotification(
        { endpoint: sub.endpoint, p256dh: sub.p256dh, auth: sub.auth },
        notificationPayload,
        vapidPublicKey,
        vapidPrivateKey
      );

      if (result.success) {
        sent++;
        console.log(`[Send Push] Success: ${sub.endpoint.substring(0, 50)}...`);
      } else {
        failed++;
        errors.push(result.error || 'Unknown error');
        console.error(`[Send Push] Failed:`, result.error);
        
        // Remove invalid/expired subscriptions
        if (result.statusCode === 410 || result.statusCode === 404) {
          console.log(`[Send Push] Removing expired subscription`);
          await supabase.from('push_subscriptions').delete().eq('endpoint', sub.endpoint);
        }
      }
    }

    console.log(`[Send Push] Result: ${sent} sent, ${failed} failed`);

    return new Response(
      JSON.stringify({ success: true, sent, failed, total: subscriptions.length, errors: errors.slice(0, 5) }),
      { status: 200, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );
  } catch (error) {
    console.error('[Send Push] General error:', error);
    return new Response(
      JSON.stringify({ error: 'Internal server error', details: error instanceof Error ? error.message : String(error) }),
      { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );
  }
});
